accounts/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_view

app_name = 'accounts'

urlpatterns = [
  path('login/', views.user_login, name='login'),
  path('logout/', auth_view.LogoutView.as_view(), name='logout'),
  path('signup/', views.Signup.as_view(), name='signup'),
  path('activate/<str:uid>/<str:token>', views.Activate.as_view(), name='activate'),
  url(r'^profile/(?P<pk>\d+)$', views.my_profile, name='my_profile'),
  url(r'^edit-profile/(?P<pk>\d+)$', views.Edit_profile.as_view(), name='edit_profile'),
  url(r'^delete/(?P<pk>\d+)$', views.delete_account, name='delete_account'),
  url(r'^warn$', views.warn, name='warn'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import RedirectView
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('projects/', include('projects.urls')),
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()

crowd_funding/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('projects', include('projects.urls')),
]

pages/urls.py
from django.urls import path, include
from . import views

app_name = 'pages'

urlpatterns = [
    path('projects/', include('projects.urls')),
    path('', views.index, name="index"),
    path('search', views.search, name="search")
]

projects/urls.py
from django.urls import path
from . import views
app_name = 'projects'

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:project_id>/', views.project_details, name="project_details"),
    path('<int:project_id>/reportProject', views.report_project, name="reportProject"),
    path('<int:project_id>/reportComment/<int:comment_id>', views.report_comment, name="reportComment"),
    path('<int:project_id>/addComment', views.new_comment, name="addComment"),
    path('<int:project_id>/deleteComment/<int:comment_id>', views.delete_comment, name="deleteComment"),
    path('<int:project_id>/editComment/<int:comment_id>', views.edit_comment, name="editComment"),
    path('<int:project_id>/updateComment/<int:comment_id>', views.update_comment, name="updateComment"),
    path('<int:project_id>/comments/<int:comment_id>/newReply', views.new_reply, name="newReply"),
    path('<int:project_id>/comments/<int:comment_id>/addReply', views.add_reply, name="addReply"),
    path('<int:project_id>/comments/<int:comment_id>/deleteReply/<int:reply_id>', views.delete_reply, name="deleteReply"),
    path('<int:project_id>/comments/<int:comment_id>/editReply/<int:reply_id>', views.edit_reply, name="editReply"),
    path('<int:project_id>/comments/<int:comment_id>/updateReply/<int:reply_id>', views.update_reply, name="updateReply"),
    path('<int:project_id>/donate', views.donate, name="donate"),
    path('delete/<int:pk>', views.delete_project, name='project_delete'),
    path('warn/<int:pk>', views.warn, name='warn'),
    path('<int:project_id>/comments/<int:comment_id>/replies/<int:reply_id>', views.report_reply, name="reportReply"),
    path('create', views.create, name="create"),

]

templates/base/_footer.html
<!-- Footer -->
  <footer id="main-footer" class="py-4 bg-dark text-white text-center">
    Copyright &copy;
    <span class="year"></span> iTi@intake39
  </footer>

templates/base/_navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
    <div class="container">
        <a class="navbar-brand" href="index.html">
            <img src="#" class="logo" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav">
                <li
                        {% if request.path == '/' %}
                            class="nav-item active mr-3"
                        {% else %}
                            class="nav-item mr-3"
                        {% endif %}
                >
                    <a class="nav-link" href="{% url 'pages:index' %}">Home</a>
                </li>
                <li
                        {% if  request.path == '/projects/' %}
                            class="nav-item active mr-3"
                        {% else %}
                            class="nav-item mr-3"
                        {% endif %}
                >
                    <a class="nav-link" href="{% url 'projects:index' %}">Projects</a>
                </li>
                <li
                        {% if  request.path == '/projects/create' %}
                            class="nav-item active mr-3"
                        {% else %}
                            class="nav-item mr-3"
                        {% endif %}
                >
                    <a class="nav-link" href="{% url 'projects:create' %}">create</a>
                </li>
            </ul>

      <ul class="navbar-nav ml-auto">
        {% if request.user.is_authenticated %}
          <li class="nav-item mr-3">
            <a class="nav-link" href="{% url 'accounts:my_profile' request.user.id %}">
              <img src="{% if request.user.image %}
                {{ request.user.image.url }}
              {% else %}
                {% static 'accounts/imgs/default.jpg' %}
              {% endif %}" style="width: 50px; height: 50px; border-radius: 50%;">
            </a>
          </li>
          <li class="nav-item mr-3">
            <a class="nav-link" href="{% url 'accounts:my_profile' request.user.id %}">
              {{ request.user.first_name }}
            </a>
          </li>
          <li class="nav-item mr-3">
            <a class="nav-link" href="{% url 'accounts:logout' %}">
              Logout
            </a>
          </li>
        {% else %}
          <li class="nav-item mr-3">
            <a class="nav-link" href="{% url 'accounts:signup' %}">
              Register
            </a>
          </li>
          <li class="nav-item mr-3">
            <a class="nav-link" href="{% url 'accounts:login' %}?next={{ request.path|urlencode }}">
              <i class="fas fa-sign-in-alt"></i>
              Login</a>
          </li>
        {% endif %}
      </ul>
    </div>
</nav>

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
  <!-- Bootstrap -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- Custom -->
  <link rel="stylesheet" href="{% static 'pages/style.css' %}">
  {% block style %}
  
  {% endblock style %}
  <title>Go Fund</title>
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
</head>

<body>
  {% include "base/_navbar.html" %}

  {% block content %}
  {% endblock content %}

  {% include "base/_footer.html" %}

   <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
    <script src="{% static 'pages/plugin.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>