accounts/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_view

app_name = 'accounts'

urlpatterns = [
  path('login/', views.user_login, name='login'),
  path('logout/', auth_view.LogoutView.as_view(), name='logout'),
  path('signup/', views.Signup.as_view(), name='signup'),
  path('activate/<str:uid>/<str:token>', views.Activate.as_view(), name='activate'),
  url(r'^profile/(?P<pk>\d+)$', views.my_profile, name='my_profile'),
  url(r'^edit-profile/(?P<pk>\d+)$', views.Edit_profile.as_view(), name='edit_profile'),
  url(r'^delete/(?P<pk>\d+)$', views.delete_account, name='delete_account'),
  url(r'^warn$', views.warn, name='warn'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import RedirectView
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('projects/', include('projects.urls')),
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()

crowd_funding/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('projects', include('projects.urls')),
]

pages/urls.py
from django.urls import path, include
from . import views

app_name = 'pages'

urlpatterns = [
    path('projects/', include('projects.urls')),
    path('', views.index, name="index"),
    path('search', views.search, name="search")
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import ugettext_lazy as _
from django.core.validators import RegexValidator


class MyUserManager(BaseUserManager):
  """
  A custom user manager to deal with emails as unique identifiers for auth
  instead of usernames. The default that's used is "UserManager"
  """

  def _create_user(self, email, password, **extra_fields):
    """
    Creates and saves a User with the given email and password.
    """
    if not email:
      raise ValueError('The Email must be set')
    email = self.normalize_email(email)
    user = self.model(email=email, **extra_fields)
    user.set_password(password)
    user.save()
    return user

  def create_superuser(self, email, password, **extra_fields):
    extra_fields.setdefault('is_staff', True)
    extra_fields.setdefault('is_superuser', True)
    extra_fields.setdefault('is_active', True)

    if extra_fields.get('is_staff') is not True:
      raise ValueError('Superuser must have is_staff=True.')
    if extra_fields.get('is_superuser') is not True:
      raise ValueError('Superuser must have is_superuser=True.')

    return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, null=True)
    image = models.ImageField(upload_to='user_images/%Y/%m/%d', blank=True, null=True)
    first_name = models.CharField(max_length=30, blank=True, null=True)
    last_name = models.CharField(max_length=30, blank=True, null=True)

    phone_regex = RegexValidator(regex=r'^01[1|0|2|5][0-9]{8}$',
                                 message="Phone number must match egyptian format")
    phone = models.CharField(validators=[phone_regex], max_length=11, blank=True)

    face_regex = RegexValidator(regex='(?:(?:http|https):\/\/)?(?:www.)?facebook.com\/(?:(?:\w)*#!\/)?(?:pages\/)?(?:[?\w\-]*\/)?(?:profile.php\?id=(?=\d.*))?([\w\-]*)?',
                                message='enter valid facebook profile url')
    facebook_profile = models.URLField(validators=[face_regex], blank=True, null=True)

    country = models.CharField(max_length=30, blank=True, null=True)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    USERNAME_FIELD = 'email'
    objects = MyUserManager()

    def __str__(self):
      return self.email

    def get_full_name(self):
      return self.email

    def get_short_name(self):
      return self.email

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, get_user_model
from .models import User
from django.core.validators import RegexValidator


class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')

    phone_regex = RegexValidator(regex=r'^01[1|0|2|5][0-9]{8}$',
                                 message="Phone number must match egyptian format")
    phone = forms.CharField(validators=[phone_regex], max_length=11, min_length=11, required=True)

    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email', 'phone', 'password1', 'password2', 'image')

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)


class EditProfileForm(forms.ModelForm):
  first_name = forms.CharField(required=True)
  last_name = forms.CharField(required=True)
  email = forms.EmailField(required=True)

  class Meta:
    model = User
    fields = ('email', 'first_name', 'last_name', 'phone', 'facebook_profile', 'country', 'image')

  def __init__(self, *args, **kwargs):
    super(EditProfileForm, self).__init__(*args, **kwargs)
    self.fields['email'].widget.attrs['readonly'] = True

accounts/views.py
from django.views import View
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .forms import SignupForm, EditProfileForm
from django.contrib.sites.shortcuts import get_current_site
from .models import User
from django.core.mail import EmailMessage
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from .tokens import account_activation_token
from django.contrib.auth import authenticate, login, logout, password_validation
from projects.models import Donation, Project, Tage
from django.views.generic import UpdateView
from django.urls import reverse_lazy


class Signup(View):
    def get(self, request):
        form = SignupForm()
        return render(request, 'accounts/signup.html', {'form': form})

    def post(self, request):
        form = SignupForm(request.POST)
        if form.is_valid():
            # Create an inactive user with no password:
            user = form.save(commit=False)
            user.image = request.FILES['image']
            user.is_active = False
            # user.set_unusable_password()
            user.save()

            # Send an email to the user with the token:
            mail_subject = 'Activate your account.'
            current_site = get_current_site(request)
            uid = urlsafe_base64_encode(force_bytes(user.pk))
            token = account_activation_token.make_token(user)
            activation_link = "{0}/?uid={1}&token{2}".format(current_site, uid, token)
            message = "Hello {0},\n {1}".format(user.first_name + " " + user.last_name, activation_link)
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')
        return redirect('accounts:signup', {form})


class Activate(View):
    def get(self, request, uidb64, token):
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except(TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        if user is not None and account_activation_token.check_token(user, token):
            # activate user and login:
            user.is_active = True
            user.save()
            return redirect('accounts:login')

        else:
            return HttpResponse('Activation link is invalid!')

    def post(self, request):
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important, to update the session with the new password
            return HttpResponse('Password changed successfully')


def user_login(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = User.objects.get(email__iexact=email)
        if not user:
            return HttpResponse("user not exist")
        if user and user.check_password(password):
            if user:
                if user.is_active:
                    login(request, user)
                    next = request.POST.get('next', '/')
                    return HttpResponseRedirect(next)
                else:
                    return HttpResponse("Your account was inactive.")
            else:
                print("Someone tried to login and failed.")
                print("They used username: {} and password: {}".format(email, password))
                return HttpResponse("Invalid login details given")
    else:
        return render(request, 'accounts/login.html', {})


def my_profile(request, pk):
    user = User.objects.filter(id=pk)[0]
    my_projects = Project.objects.filter(user=request.user)
    my_donations = Donation.objects.filter(user=request.user)
    for i in my_projects:
        i.tags = Tage.objects.filter(project=i.id)
        i.donation = Donation.objects.filter(user=request.user,project=i.id)
        for d in i.donation:
            print(d.amount)
    context = {
        'user': user,
        'projects': my_projects,
        'donations': my_donations,
    }

    return render(request, 'accounts/profile.html', context)


# edit user profile
class Edit_profile(UpdateView):
    form_class = EditProfileForm
    template_name = 'accounts/edit_profile.html'

    def get_success_url(self):
        return reverse_lazy('accounts:my_profile', kwargs={'pk': self.kwargs['pk']})

    def get_object(self, queryset=None):
        obj = User.objects.get(id=self.kwargs['pk'])
        return obj


def warn(request):
    context = {
        'cancel': 'accounts:my_profile',
        'delete': 'accounts:delete_account',
        'msg': 'Are you sure you want to delete your account ? All your projects and donations will be deleted',
        'cancel_id': request.user.id,
        'delete_id': request.user.id,
    }
    return render(request, 'accounts/warn.html', context)


def delete_account(request, pk):
    user = User.objects.get(id=pk);
    logout(request)
    user.delete()
    return redirect('pages:index')

accounts/templates/accounts/edit_profile.html
{% extends 'base/base.html' %}
{% load static %}
<style>
  input[name='email']{
    border: none;
    outline: none;
    font-size: 25px;
    text-align: center;
    color: #FF643C;
  }
</style>

{% block content %}
  <div style="background-color: white; text-align: center">
    <h2 style="padding-top: 20px; color: #FF643C">Edit your profile</h2>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% for field in form %}
        <p>
          <h5 style="margin: 0; padding: 0;">{{ field.label_tag }}</h5>
          {{ field}}
          {% if field.help_text %}
            <small style="color: grey">{{ field.help_text }}</small>
          {% endif %}
          {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
          {% endfor %}
        </p>
      {% endfor %}
      <button class="btn btn-primary" type="submit">Submit</button>
    </form>
    <br>
  </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "base/base.html" %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-8 login-form">
      {% if form.errors %}
        <p style="color: red;">{{ form.errors }}</p>
      {% endif %}
      <form method="post" >
        {% csrf_token %}
        <input type="hidden", name="next" value="{{ next }}"/>
        <div class="form-group">
          <label for="exampleInputEmail1">Email address</label>
          <input type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
          <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
          <input type="password" name="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
        </div>
        <input type="hidden" name="next" value="{{ request.GET.next }}">
        <button type="submit" class="btn btn-primary">Login</button>
      </form>
      </div>
    </div>
  </div>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}

    <div class="card ml-5 mr-5" style="width: 22rem;float: left; margin-top: 5rem;">
        <img class="card-img-top" src="{% if user.image %}
                 {{ user.image.url }}
               {% else %}
                 {% static 'accounts/imgs/default.jpg' %}
               {% endif %}" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">FirstName:- {{ user.first_name }}</h5>
            <h5 class="card-title">LastName:- {{ user.last_name }}</h5>
            <h5 class="card-title">Email:- {{ user.email }}</h5>
            <h5 class="card-title">Phone:- {{ user.phone }}</h5>
            {% if user.facebook_profile %}
                <h5 class="card-title">Facebook profile:-
                    <a href="{{ user.facebook_profile }}">
                        {{ user.facebook_profile }}
                    </a>
                </h5>
            {% endif %}
            {% if user.country %}
                <h5 class="card-title">Country:- {{ user.country }}</h5>
            {% endif %}
        </div>
        {% if request.user == user %}
            <a class="btn btn-warning" href="{% url 'accounts:edit_profile' user.id %}">Update my profile</a>
            <a style="margin-top: 1rem;" class="btn btn-danger" href="{% url 'accounts:warn' %}">Delete my account</a>
        {% endif %}
    </div>
    <div class="row">

        <div class="col-10" style="width: 50rem; float: left;margin-top: 2rem;">
            <h2 style="text-align: center;">my Projects</h2>
            <table class="table table-dark table-striped">
                <thead>
                <tr>
                    <th>title</th>
                    <th>Donation</th>
                    <th>Category</th>
                    <th>Tages</th>
                </tr>
                </thead>
                <tbody>
                {% for p in projects %}
                    <tr>
                        <td>{{ p.title }}</td>
                        <td>{{ p.category }}</td>
                        <td>
                            {% for t in p.tags %}
                                {{ t.name }} ,
                            {% endfor %}
                        </td>
                        <td>
                            {% for t in p.donation %}
                                <span style="">{{ t.amount }} </span>
                            {% endfor %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
{#        <div style="width: 50rem; float: right;margin-top: 2rem;margin-right: 10rem;">#}
{#            <h2 style="text-align: center;">my Donations</h2>#}
{#            <table class="table table-dark table-striped">#}
{#                <thead>#}
{#                <tr>#}
{#                    <th>Project</th>#}
{#                    <th>Amount</th>#}
{#                </tr>#}
{#                </thead>#}
{#                <tbody>#}
{#                {% for d in donations %}#}
{#                    <tr>#}
{#                        <td>{{ d.project.title }}</td>#}
{#                        <td>{{ d.amount }}</td>#}
{#                    </tr>#}
{#                {% endfor %}#}
{#                </tbody>#}
{#            </table>#}
{#        </div>#}
    </div>

    <div style="clear: both;"></div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base/base.html" %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-8 login-form">
        {% if form.errors %}
          <p style="color: red;">{{ form.errors }}</p>
        {% endif %}
        <form method="post" class="signup-form" enctype="multipart/form-data">
          {% csrf_token %}
          {% for field in form %}
            <p>
              {{ field.label_tag }}<br>
              {{ field }}
              {% if field.help_text %}
                <br>
                <small style="color: grey;">{{ field.help_text }}</small>
              {% endif %}
              {% for error in field.errors %}
                <p style="color: red">{{ error }}</p>
              {% endfor %}
            </p>
          {% endfor %}
          <button type="submit">Sign up</button>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

accounts/templates/accounts/warn.html
{% extends 'base/base.html' %}

{% block content %}
  <div style="text-align: center;" class="container">
    <h1 style="color: red;">are you sure?</h1>
    <div style="text-align: center;" class="alert alert-danger" role="alert">
      {{ msg }}
    </div>

    <a style="margin: 2rem;" class="btn btn-danger"
       href="{% url delete delete_id %}">Yes, I'm Sure</a>
    <a style="margin: 2rem;" class="btn btn-secondary"
       href="{% url cancel cancel_id %}">No, Take me back
    </a>
  </div>
{% endblock %}