config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import RedirectView
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('projects/', include('projects.urls')),
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()

crowd_funding/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('projects', include('projects.urls')),
]

pages/urls.py
from django.urls import path, include
from . import views

app_name = 'pages'

urlpatterns = [
    path('projects/', include('projects.urls')),
    path('', views.index, name="index"),
    path('search', views.search, name="search")
]

projects/urls.py
from django.urls import path
from . import views
app_name = 'projects'

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:project_id>/', views.project_details, name="project_details"),
    path('<int:project_id>/reportProject', views.report_project, name="reportProject"),
    path('<int:project_id>/reportComment/<int:comment_id>', views.report_comment, name="reportComment"),
    path('<int:project_id>/addComment', views.new_comment, name="addComment"),
    path('<int:project_id>/deleteComment/<int:comment_id>', views.delete_comment, name="deleteComment"),
    path('<int:project_id>/editComment/<int:comment_id>', views.edit_comment, name="editComment"),
    path('<int:project_id>/updateComment/<int:comment_id>', views.update_comment, name="updateComment"),
    path('<int:project_id>/comments/<int:comment_id>/newReply', views.new_reply, name="newReply"),
    path('<int:project_id>/comments/<int:comment_id>/addReply', views.add_reply, name="addReply"),
    path('<int:project_id>/comments/<int:comment_id>/deleteReply/<int:reply_id>', views.delete_reply, name="deleteReply"),
    path('<int:project_id>/comments/<int:comment_id>/editReply/<int:reply_id>', views.edit_reply, name="editReply"),
    path('<int:project_id>/comments/<int:comment_id>/updateReply/<int:reply_id>', views.update_reply, name="updateReply"),
    path('<int:project_id>/donate', views.donate, name="donate"),
    path('delete/<int:pk>', views.delete_project, name='project_delete'),
    path('warn/<int:pk>', views.warn, name='warn'),
    path('<int:project_id>/comments/<int:comment_id>/replies/<int:reply_id>', views.report_reply, name="reportReply"),
    path('create', views.create, name="create"),

]

projects/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator
from accounts.models import User
from taggit.managers import TaggableManager


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Project(models.Model):
    title = models.CharField(max_length=200)
    details = models.TextField(blank=True)
    target = models.IntegerField()
    start_time = models.DateTimeField(auto_now_add=True, blank=True)
    end_time = models.DateTimeField()
    featured = models.BooleanField(default=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.title

    # tages = TaggableManager()

    class Meta:
        ordering = ('title',)


class Tage(models.Model):
    name = models.CharField(max_length=200)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    # class Meta:
    #     ordering = ('tages',)
    #
    # def __str__(self):
    #     return self.tages


# def get_image_filename(instance, filename):
#     id = instance.Project.id
#     return "post_images/%s" % (id)

class Picture(models.Model):
    image = models.ImageField(upload_to='photos/')
    project = models.ForeignKey(Project, on_delete=models.CASCADE)


class Comment(models.Model):
    body = models.TextField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Reply(models.Model):
    body = models.TextField()
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Donation(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.IntegerField()


class Rate(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField(
        blank=True, validators=[MinValueValidator(1), MaxValueValidator(100)])


class InAppropriateProject(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True)
   


class InAppropriateComment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, null=True)
   


class InAppropriateReply(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    reply = models.ForeignKey(Reply, on_delete=models.CASCADE, null=True)
   
 

pages/templates/pages/index.html
{% extends "base/base.html" %}

{% block content %}

  <div class="row">
    <div class="col-md-12 mt-4">
      {% if highest_five_rated %}
        <div id="demo" class="carousel slide" data-ride="carousel">
          <ul class="carousel-indicators">
            <li data-target="#demo" data-slide-to="0" class="active"></li>
            <li data-target="#demo" data-slide-to="1"></li>
            <li data-target="#demo" data-slide-to="2"></li>
            <li data-target="#demo" data-slide-to="3"></li>
            <li data-target="#demo" data-slide-to="4"></li>
          </ul>
          <div class="carousel-inner">

            {% for project in  highest_five_rated %}
              <div {% if forloop.counter0 == 0 %} class="carousel-item active" {% else %}
                                                  class="carousel-item" {% endif %}>
                {% for picture in project.picture_set.all|slice:":1" %}
                  <img src="{{ picture.image.url }}" alt="Los Angeles" width="1100" height="500">
                {% endfor %}
                <div class="carousel-caption">
                  <h3>Los Angeles</h3>
                  <p>We had such a great time in LA!</p>
                </div>
              </div>
            {% endfor %}


          </div>
          <a class="carousel-control-prev" href="#demo" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
          </a>
          <a class="carousel-control-next" href="#demo" data-slide="next">
            <span class="carousel-control-next-icon"></span>
          </a>
        </div>

      {% else %}
        {% if 'search' not in request.path %}
          <div class="col-md-12">highest five not available</div>
        {% endif %}
      {% endif %}
    </div>
  </div>


  <div class="container">
    <div class="row">
      <div class="row col-md-12 mt-4">
        <form class="row col-12 example text-center" action="{% url 'pages:search' %}">
          <div class="offset-3 col-5 row">
            <input class="col-12" id="search_input" name="search" type="text" placeholder="Search.." name="search">
          </div>
          <div class="col-2 row">
            <button class="col-12" id="search_btn" type="submit"><i class="fa fa-search"></i></button>
          </div>
        </form>
      </div>
    </div>
  </div>

  <!--start of search-->
  <section id="projects_search" class="py-4">
    <div class="container">
      <div class="row">
        {% if projects_search %}
          {% for project in projects_search %}
            <div class="col-md-6 col-lg-4 mb-4">
              <div class="card">
                {% for picture in project.picture_set.all|slice:":1" %}
                  <img class="card-img-top" src="{{ picture.image.url }}" alt="image not available">
                {% endfor %}
                <div>
                  <h2>
                    <span class="badge badge-secondary text-white">${{ project.target }}</span>
                  </h2>
                </div>
                <div class="card-body">
                  <div class="text-center">
                    <h5 class="text-primary">{{ project.title }}</h5>
                    <h6 class="text-primary">Owner: {{ project.user.first_name }}</h6>
                    <p>Category: {{ project.category }}</p>
                  </div>
                  <hr>
                  <div class="row py-1 text-secondary">
                    <div class="col-6">
                      <div>Start</div>
                      <div>{{ project.start_time }}</div>
                    </div>
                    <div class="col-6">
                      <div>End</div>
                      <div>{{ project.end_time }}</div>
                    </div>
                  </div>
                  <hr>
                  <a href="{% url 'projects:project_details' project.id %}" class="btn btn-primary btn-block">More
                    Info</a>
                </div>
              </div>
            </div>
          {% endfor %}
        {% else %}

        {% endif %}
      </div>
    </div>
  </section>

  <!--end of search-->

  <!--start of latest five-->
  <section id="latest_five_projects" class="py-4">
    <div class="container">
      {% if 'search' not in request.path %}
        <div class="h1 text-center">Latest Five Projects</div>
      {% endif %}
      <div class="row">
        {% if latest_five %}
          {% for project in latest_five %}
            <div class="col-md-6 col-lg-4 mb-4">
              <div class="card">
                {% for picture in project.picture_set.all|slice:":1" %}
                  <img class="card-img-top" src="{{ picture.image.url }}" alt="image not available">
                {% endfor %}
                <div>
                  <h2>
                    <span class="badge badge-secondary text-white">${{ project.target }}</span>
                  </h2>
                </div>
                <div class="card-body">
                  <div class="text-center">
                    <h5 class="text-primary">{{ project.title }}</h5>
                    <h6 class="text-primary">Owner: {{ project.user.first_name }}</h6>
                    <p>Category: {{ project.category }}</p>
                  </div>
                  <hr>
                  <div class="row py-1 text-secondary">
                    <div class="col-6">
                      <div>Start</div>
                      <div>{{ project.start_time }}</div>
                    </div>
                    <div class="col-6">
                      <div>End</div>
                      <div>{{ project.end_time }}</div>
                    </div>
                  </div>
                  <hr>
                  <a href="{% url 'projects:project_details' project.id %}" class="btn btn-primary btn-block">More
                    Info</a>
                </div>
              </div>
            </div>
          {% endfor %}
        {% else %}
          {% if 'search' not in request.path %}
            <h1>No Projects Available</h1>
          {% endif %}
        {% endif %}
      </div>
    </div>
  </section>
  <!--end of latest five-->

  <!--start of featured five-->
  <section id="latest_five_projects" class="py-4">
    <div class="container">
      <div class="row">
        {% if featured_five %}
          <div class="h1 text-center col-md-12"> Featured Projects</div>
          {% for project in featured_five %}
            <div class="col-md-6 col-lg-4 mb-4">
            <div class="card">
              {% for picture in project.picture_set.all|slice:":1" %}
                <img class="card-img-top" src="{{ picture.image.url }}" alt="image not available">
              {% endfor %}
              <div>
                <h2>
                  <span class="badge badge-secondary text-white">${{ project.target }}</span>
                </h2>
                <div class="card-body">
                  <div class="text-center">
                    <h5 class="text-primary">{{ project.title }}</h5>
                    <h6 class="text-primary">Owner: {{ project.user.first_name }}</h6>
                    <p>Category: {{ project.category }}</p>
                  </div>
                  <hr>
                  <div class="row py-1 text-secondary">
                    <div class="col-6">
                      <div>Start</div>
                      <div>{{ project.start_time }}</div>
                    </div>
                    <div class="col-6">
                      <div>End</div>
                      <div>{{ project.end_time }}</div>
                    </div>
                  </div>
                  <hr>
                  <a href="{% url 'projects:project_details' project.id %}" class="btn btn-primary btn-block">More
                    Info</a>
                </div>
              </div>
            </div>
          {% endfor %}
        {% else %}
          {% if 'search' not in request.path %}
            <h1>No Featured Available</h1>
          {% endif %}
        {% endif %}
        </div>
      </div>
  </section>
  <!--end of featured five-->

{% endblock content %}