config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import RedirectView
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('projects/', include('projects.urls')),
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()

crowd_funding/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('projects', include('projects.urls')),
]

pages/urls.py
from django.urls import path, include
from . import views

app_name = 'pages'

urlpatterns = [
    path('projects/', include('projects.urls')),
    path('', views.index, name="index"),
    path('search', views.search, name="search")
]

projects/urls.py
from django.urls import path
from . import views
app_name = 'projects'

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:project_id>/', views.project_details, name="project_details"),
    path('<int:project_id>/reportProject', views.report_project, name="reportProject"),
    path('<int:project_id>/reportComment/<int:comment_id>', views.report_comment, name="reportComment"),
    path('<int:project_id>/addComment', views.new_comment, name="addComment"),
    path('<int:project_id>/deleteComment/<int:comment_id>', views.delete_comment, name="deleteComment"),
    path('<int:project_id>/editComment/<int:comment_id>', views.edit_comment, name="editComment"),
    path('<int:project_id>/updateComment/<int:comment_id>', views.update_comment, name="updateComment"),
    path('<int:project_id>/comments/<int:comment_id>/newReply', views.new_reply, name="newReply"),
    path('<int:project_id>/comments/<int:comment_id>/addReply', views.add_reply, name="addReply"),
    path('<int:project_id>/comments/<int:comment_id>/deleteReply/<int:reply_id>', views.delete_reply, name="deleteReply"),
    path('<int:project_id>/comments/<int:comment_id>/editReply/<int:reply_id>', views.edit_reply, name="editReply"),
    path('<int:project_id>/comments/<int:comment_id>/updateReply/<int:reply_id>', views.update_reply, name="updateReply"),
    path('<int:project_id>/donate', views.donate, name="donate"),
    path('delete/<int:pk>', views.delete_project, name='project_delete'),
    path('warn/<int:pk>', views.warn, name='warn'),
    path('<int:project_id>/comments/<int:comment_id>/replies/<int:reply_id>', views.report_reply, name="reportReply"),
    path('create', views.create, name="create"),

]

projects/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator
from accounts.models import User
from taggit.managers import TaggableManager


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Project(models.Model):
    title = models.CharField(max_length=200)
    details = models.TextField(blank=True)
    target = models.IntegerField()
    start_time = models.DateTimeField(auto_now_add=True, blank=True)
    end_time = models.DateTimeField()
    featured = models.BooleanField(default=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.title

    # tages = TaggableManager()

    class Meta:
        ordering = ('title',)


class Tage(models.Model):
    name = models.CharField(max_length=200)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    # class Meta:
    #     ordering = ('tages',)
    #
    # def __str__(self):
    #     return self.tages


# def get_image_filename(instance, filename):
#     id = instance.Project.id
#     return "post_images/%s" % (id)

class Picture(models.Model):
    image = models.ImageField(upload_to='photos/')
    project = models.ForeignKey(Project, on_delete=models.CASCADE)


class Comment(models.Model):
    body = models.TextField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Reply(models.Model):
    body = models.TextField()
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Donation(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.IntegerField()


class Rate(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField(
        blank=True, validators=[MinValueValidator(1), MaxValueValidator(100)])


class InAppropriateProject(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True)
   


class InAppropriateComment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, null=True)
   


class InAppropriateReply(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    reply = models.ForeignKey(Reply, on_delete=models.CASCADE, null=True)
   
 

projects/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.http import HttpResponse
from .formCreat import CreateProject
from .models import Comment, Project, Reply, Tage, Picture, Category, Donation, InAppropriateProject, \
    InAppropriateComment, InAppropriateReply

from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.core.paginator import Paginator


# Create your views here.


def index(request):
    projects_list = Project.objects.all()
    paginator = Paginator(projects_list, 9)
    page = request.GET.get('page')
    projects = paginator.get_page(page)
    report_projects = InAppropriateProject.objects.filter(
        user_id=request.user.id)
    print("====================")
    print(report_project)
    context = {
        'projects': projects,
        'report_projects': report_projects,
    }
    return render(request, 'projects/index.html', context)


def project_details(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    picture = Picture.objects.all().filter(project_id=project_id)
    # return HttpResponse(picture)

    report_projects = InAppropriateProject.objects.filter(
        user_id=request.user.id, project_id=project_id)

    report_comments = InAppropriateComment.objects.filter(
        user_id=request.user.id).values("comment_id")

    report_replies = InAppropriateReply.objects.filter(
        user_id=request.user.id).values("reply_id")
    print("*************")
    report_comment_ids = []
    report_reply_ids = []
    for c in report_comments:
        report_comment_ids.append(c['comment_id'])
    for r in report_replies:
        report_reply_ids.append(r['reply_id'])
    print(report_comment_ids)
    print(report_reply_ids)
    donations = Donation.objects.all().filter(project_id=project_id)
    reached_target = Donation.objects.filter(
        project_id=project_id).aggregate(total=Sum('amount'))
    print(reached_target)
    if reached_target['total']:
        percent = round(reached_target['total'] * 100 / project.target, 2)
    else:
        percent = 0

    return render(request, 'projects/project_details.html', {
        'project': project,
        'picture': picture[0],
        'donations': donations,
        'percent': percent,
        'report_projects': report_projects,
        'report_comment_ids': report_comment_ids,
        'report_reply_ids': report_reply_ids,
        "pictures": picture
    })


def new_comment(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    comment = Comment(
        user_id=request.user.id,
        body=request.POST['body'],
        project_id=project_id)
    comment.save()
    return redirect('projects:project_details', project_id=project_id)


def delete_comment(request, comment_id, project_id):
    Comment.objects.filter(pk=comment_id).delete()
    project = get_object_or_404(Project, pk=project_id)
    return redirect('projects:project_details', project_id=project_id)


def edit_comment(request, comment_id, project_id):
    project = Project.objects.get(pk=project_id)
    comment = Comment.objects.get(pk=comment_id)
    picture = Picture.objects.all().filter(project_id=project_id)
    return render(request, 'projects/edit_comment.html',
                  {'project': project, 'comment_id': comment_id, 'picture': picture[0]})


def update_comment(request, comment_id, project_id):
    body = request.POST['body']
    Comment.objects.filter(pk=comment_id).update(body=body)
    project = get_object_or_404(Project, pk=project_id)
    return redirect('projects:project_details', project_id=project_id)


def new_reply(request, comment_id, project_id):
    project = get_object_or_404(Project, pk=project_id)
    picture = Picture.objects.all().filter(project_id=project_id)
    report_comments = InAppropriateComment.objects.filter(
        user_id=request.user.id).values("comment_id")

    report_replies = InAppropriateReply.objects.filter(
        user_id=request.user.id).values("reply_id")
    report_comment_ids = []
    report_reply_ids = []
    for c in report_comments:
        report_comment_ids.append(c['comment_id'])
    for r in report_replies:
        report_reply_ids.append(r['reply_id'])
    return render(request, 'projects/new_reply.html',
                  {'comment_id': comment_id,
                   'project': project,
                   'picture': picture[0],
                   'report_comment_ids': report_comment_ids,
                   'report_reply_ids': report_reply_ids})


def add_reply(request, comment_id, project_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    reply = Reply(
        user_id=request.user.id, body=request.POST['body'],
        comment_id=comment_id)
    reply.save()
    return redirect('projects:project_details', project_id=project_id)


def delete_reply(request, comment_id, project_id, reply_id):
    Reply.objects.filter(pk=reply_id).delete()
    project = get_object_or_404(Project, pk=project_id)
    return redirect('projects:project_details', project_id=project_id)


def edit_reply(request, comment_id, project_id, reply_id):
    project = Project.objects.get(pk=project_id)
    comment = Comment.objects.get(pk=comment_id)
    picture = Picture.objects.all().filter(project_id=project_id)

    report_replies = InAppropriateReply.objects.filter(
        user_id=request.user.id).values("reply_id")
    report_reply_ids = []
    for r in report_replies:
        report_reply_ids.append(r['reply_id'])

    return render(request, 'projects/edit_reply.html',
                  {'project': project,
                   'comment_id': comment_id,
                   'reply_id': reply_id,
                   'picture': picture[0],
                   'report_reply_ids': report_reply_ids
                   })


def update_reply(request, comment_id, project_id, reply_id):
    body = request.POST['body']
    Reply.objects.filter(pk=reply_id).update(body=body)
    project = get_object_or_404(Project, pk=project_id)
    return redirect('projects:project_details', project_id=project_id)


def update_reply(request, comment_id, project_id, reply_id):
    body = request.POST['body']
    Reply.objects.filter(pk=reply_id).update(body=body)
    project = get_object_or_404(Project, pk=project_id)
    return redirect('projects:project_details', project_id=project_id)


@login_required()
def create(request):
    category = Category.objects.all()
    if request.method == 'POST':
        form = CreateProject(request.POST)
        if form:
            project = Project()
            project.user_id = request.user.id
            project.title = form['title'].value()
            project.target = int(form['target'].value())
            project.details = form['details'].value()
            project.end_time = form['endTiem'].value()
            project.category_id = int(request.POST['category'])
            # project.tages = form['tages'].value()
            project.save()
            if project.id:
                allTags = form['tages'].value().split(',')
                for onetag in allTags:
                    tag = Tage()
                    tag.name = onetag
                    tag.project_id = project.id
                    tag.save()
                if request.FILES['Images']:
                    for i in request.FILES.getlist('Images'):
                        picture = Picture()
                        picture.project_id = project.id
                        picture.image = i
                        picture.save()
                    form = CreateProject()
                    if picture.id:
                        contextpost = {
                            'form': form,
                            'category': category,
                            'done': "broject has been created and picture saved"
                        }
                        return render(request, 'projects/create.html', contextpost)
                    else:
                        contextpost = {
                            'form': form,
                            'category': category,
                            'done': "broject has been created and picture dose not saved"
                        }
            return render(request, 'projects/create.html', contextpost)
        else:
            contextpost = {
                'form': form,
                'category': category,
                'done': "noooooooooooooooooooooooo"
            }
            return render(request, 'projects/create.html', contextpost)
        # return HttpResponse(form.fields)
    else:
        form = CreateProject()
        contextget = {
            'form': form,
            'category': category,
        }
        return render(request, 'projects/create.html', contextget)


def donate(request, project_id):
    if request.POST.get('donation'):
        project = get_object_or_404(Project, pk=project_id)
        donation = Donation(
            user_id=request.user.id,
            amount=request.POST['donation'],
            project_id=project_id)
        donation.save()
        return redirect('projects:project_details', project_id=project_id)
    else:
        return redirect('projects:project_details', project_id=project_id)


def report_project(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    in_appropriate_project = InAppropriateProject(
        user_id=request.user.id,
        project_id=project_id)
    in_appropriate_project.save()
    return redirect('projects:index')


def report_comment(request, project_id, comment_id):
    # project = get_object_or_404(Project, pk=project_id)
    in_appropriate_comment = InAppropriateComment(
        user_id=request.user.id,
        comment_id=comment_id)
    in_appropriate_comment.save()
    return redirect('projects:project_details', project_id=project_id)

projects/templates/projects/edit_reply.html
{% extends "base/base.html" %}

{% block content %}
  <div class="container">
    <h3 class="display-3 text-center">{{ project.title }}</h3>
    <img src="{{ picture.image.url }}" class="rounded mx-auto d-block" width="300" height="300"/><br/>
    <strong>Target : </strong><span class="text-primary">{{ project.target }}$</span> |
    <strong>Start Time : </strong><span class="text-primary">{{ project.start_time }}</span> |
    <strong>End Time : </strong><span class="text-primary">{{ project.end_time }}</span> <br/>
    <strong>Created By : </strong><span
      class="text-primary">{{ project.user.first_name }} {{ project.user.last_name }}</span><br/>
    <strong>Category : </strong><span class="text-primary">{{ project.category.name }}</span> <br/>
    <hr>
    <p class="font-weight-bold text-dark"> {{ project.details }}</p>
    <h5 class="font-weight-bold text-dark"> comments : </h5></br>

    <div class="rounded bg-light">
      {% for comment in project.comment_set.all %}
        {% if comment_id == comment.id %}
          <div class="p-3 mb-2 bg-dark text-white rounded">
            <span class="font-weight-bold text-primary">
                 {{ comment.user.first_name }} {{ comment.user.last_name }} :
            </span>
            <span>{{ comment.body }}</span>
            <div class="float-right">
              {% if comment.user.id == request.user.id %}
                <a href="{% url 'projects:deleteComment' comment.project.id comment.id %}">
                  <i class="fa fa-trash fa-lg" aria-hidden="true"></i>
                </a>
                <a href="{% url 'projects:editComment' comment.project.id comment.id %}">
                  <i class="fa fa-edit fa-lg" aria-hidden="true"></i>
                </a>
              {% else %}
                <a href="{% url 'projects:reportComment' comment.project.id comment.id %}">
                  <i class="fa fa-ban text-danger fa-lg "></i>
                </a>
              {% endif %}
            </div>
            <br/>
            {% for reply in comment.reply_set.all %}
              {% if report_reply_ids and reply.id in report_reply_ids %}

              {% else %}
                {% if reply_id == reply.id %}
                  <div class="form-group col-xs-6">
                    <form class="form-group"
                          action="{% url 'projects:updateReply' reply.comment.project.id reply.comment.id reply.id %}"
                          method="post">
                      {% csrf_token %}
                      <input class="form-control input-md" value="{{ reply.body }}" type="text" name="body"/>
                      <input class="btn btn-primary" type="submit" value="Edit" name="submit"/>
                    </form>
                  </div>
                {% else %}
                  <p style="margin-left:5%">
              <span class="font-weight-bold text-primary">
                  {{ reply.user.first_name }} {{ reply.user.last_name }} :
              </span>
                    <span>{{ reply.body }}</span>
                    {% if reply.user.id == request.user.id %}
                      <a href="{% url 'projects:deleteReply'  reply.comment.project.id reply.comment.id reply.id %}">
                        <i class="fa fa-trash fa-lg " aria-hidden="true"></i>
                      </a>
                    {% endif %}
                  </p>
                {% endif %}
              {% endif %}
            {% endfor %}

            <a style="margin-left:5%;margin-bottom:2% " class="btn btn-primary" role="button"
               href="{% url 'projects:newReply' comment.project.id comment.id %}">Add Reply</a><br/>
          </div>
        {% endif %}
      {% endfor %}
    </div>
  </div>
{% endblock content %}

projects/templates/projects/new_reply.html
{% extends "base/base.html" %}

{% block content %}
    <div class="container">
        <h3 class="display-3 text-center" >{{ project.title }}</h3>
        <img src="{{ picture.image.url }}" class="rounded mx-auto d-block" width="300" height="300" /><br />
        <strong>Target : </strong><span class="text-primary">{{ project.target }}$</span> | 
        <strong>Start Time : </strong><span class="text-primary">{{ project.start_time }}</span> | 
        <strong>End Time : </strong><span class="text-primary">{{ project.end_time }}</span> <br />
        <strong>Created By : </strong><span class="text-primary">{{ project.user.first_name }} {{ project.user.last_name }}</span><br />
        <strong>Category : </strong><span class="text-primary">{{ project.category.name }}</span> <br />
        <hr>
        <p class="font-weight-bold text-dark" > {{ project.details }}</p>
            <h5 class="font-weight-bold text-dark" > comments : </h5></br>
            <div class=" rounded bg-light">
                    {% for comment in project.comment_set.all %}
                     {% if report_comment_ids and comment.id in report_comment_ids %} 
                     {% else %}
                   <div class="p-3 mb-2 bg-dark text-white rounded">
                        <span class="font-weight-bold text-primary" > 
                                {{ comment.user.first_name }} {{ comment.user.last_name }} :
                            </span>
                            <span>{{ comment.body }}</span>
                            <div class="float-right">
                            {% if request.user.id == comment.user.id %}
                            <a href="{% url 'projects:deleteComment' comment.project.id comment.id %}">
                                    <i class="fa fa-trash fa-lg " aria-hidden="true"></i>
                            </a>
                            <a href="{% url 'projects:editComment' comment.project.id comment.id %}">
                                    <i class="fa fa-edit fa-lg " aria-hidden="true"></i>
                            </a>
                            {% else %}
                            <a href="{% url 'projects:reportComment' comment.project.id comment.id %}">
                                    <i class="fa fa-ban text-danger fa-lg "></i>
                                </a>
                            {% endif %}
                            </div>
                            <br/>
                            {% for reply in comment.reply_set.all%}
                            {% if report_reply_ids and reply.id in report_reply_ids %}

                            {% else %}        
                                <p style="margin-left:5%">
                                    <span class="font-weight-bold text-primary" > 
                                        {{ reply.user.first_name }} {{ reply.user.last_name }} :
                                    </span>
                                    <span>{{ reply.body }}</span>
                                </p>
                                {% endif %}
                            {% endfor%}
                    
                           
                            {% if comment_id == comment.id  %}
                            <form class="form-group" action="{% url 'projects:addReply' comment.project.id comment.id %}" method="post">
                                    {% csrf_token %}
                                 <input  style="margin-left:5%" type="text" class="form-control input-sm" placeholder="Add Reply ..." value="" name="body" />
                                <input type="submit" class="btn btn-primary" value="Add" name="submit" />
                            </form>
                            {% else %}
                            <a style="margin-left:5%;margin-bottom:2% " class="btn btn-primary" role="button" href="{% url 'projects:newReply' comment.project.id comment.id %}" >Add Reply</a><br />
                            {% endif %}

                   </div>
                   {% endif %}
                    {% endfor %}
            
                    <form action="{% url 'projects:addComment' project.id %}" method="post">
                        {% csrf_token %}
                        <input class="form-control input-lg" placeholder="Add Comment ..." type="text" name="body" />
                        <input type="submit" class="btn btn-primary" value="Add" name="submit" />
                    </form>

            </div>
       
    </div>
{% endblock content %}

projects/templates/projects/project_details.html
{% extends "base/base.html" %}
{% load ratings %}

{% block content %}
  <div class="container">
  {% if report_projects %}
    <h1>Not Available</h1>
  {% else %}
    <div class="container">
    <h3 class="display-3 text-center">{{ project.title }}</h3>
    <img src="{{ picture.image.url }}" class="rounded mx-auto d-block" width="300" height="300"/><br/>
    <strong>Target : </strong><span class="text-primary">{{ project.target }}$</span> |
    <strong>Start Time : </strong><span class="text-primary">{{ project.start_time }}</span> |
    <strong>End Time : </strong><span class="text-primary">{{ project.end_time }}</span> <br/>
    <strong>Created By : </strong><span
      class="text-primary">{{ project.user.first_name }} {{ project.user.last_name }}</span><br/>
    <strong>Category : </strong><span class="text-primary">{{ project.category.name }}</span> <br/>
    <form class="form-group" action="{% url 'projects:reportProject' project.id %}" method="post">
      {% csrf_token %}
      <input type="submit" class="btn btn-danger btn-md pull-right" value="Report Project"/><br/>
    </form>
    <hr>
    <p class="font-weight-bold text-dark"> {{ project.details }}</p>
    {% ratings project %}
    {% if request.user == project.user %}
      <br>
      <a style="margin-top: 1rem;margin-bottom: 1rem;" class="btn btn-danger"
         href="{% url 'projects:warn' project.id %}">Delete project</a>
    {% endif %}
    <!--start of target-->
    <div class="donaitors">
      <table class="table">
        <thead class="thead-dark">
        <tr>
          <th scope="col">Total Target</th>
          <th scope="col">Reached Target</th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td> {{ project.target }} </td>
          <td> {{ percent }}%</td>
        </tr>
        </tbody>
      </table>
    </div>
    <!--end of target-->


    {% if request.user.is_authenticated and request.user.id != project.user.id %}
      <!--start add donation-->
      <div class="form-group col-xs-6">
        <form class="form-group" action="{% url 'projects:donate' project.id %}" method="post">
          {% csrf_token %}
          <input class="form-control input-md" placeholder="Donation amount" type="text" name="donation"/>
          <input class="btn btn-primary" type="submit" value="Donate" name="submit"/>
        </form>
      </div>
      <!--end add donation-->
    {% endif %}

    <!--start donaitors table-->
    {% if donations %}
      <div class="donaitors">
        <table class="table">
          <thead class="thead-dark">
          <tr>
            <th scope="col">Donation</th>
            <th scope="col">Username</th>
            <th scope="col">amount</th>
          </tr>
          </thead>
          <tbody>
          {% for donation in donations %}
            <tr>
              <th scope="row">{{ forloop.counter }}</th>
              <td> {{ donation.user.first_name }} </td>
              <td> {{ donation.amount }}</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    {% else %}
      <div class="alert alert-info" role="alert">
        No donation for this project
      </div>
    {% endif %}
    <!--send donaitors table-->



    <h5 class="font-weight-bold text-dark"> comments : </h5></br>
    <div class=" rounded bg-light">
      {% for comment in project.comment_set.all %}
        {% if report_comment_ids and comment.id in report_comment_ids %}

        {% else %}
          <div class="p-3 mb-2 bg-dark text-white rounded">
              <span
                  class="font-weight-bold text-primary"> {{ comment.user.first_name }} {{ comment.user.last_name }} :</span>
            <span>{{ comment.body }}</span>
            <div class="float-right">
              {% if comment.user.id == request.user.id %}
                <a href="{% url 'projects:deleteComment' comment.project.id comment.id %}">
                  <i class="fa fa-trash fa-lg " aria-hidden="true"></i>
                </a>
                <a href="{% url 'projects:editComment' comment.project.id comment.id %}">
                  <i class="fa fa-edit fa-lg " aria-hidden="true"></i>
                </a>
              {% else %}
                <a href="{% url 'projects:reportComment' comment.project.id comment.id %}">
                  <i class="fa fa-ban text-danger fa-lg "></i>
                </a>
              {% endif %}
            </div>


            <br/>

            {% for reply in comment.reply_set.all %}
              {% if report_reply_ids and reply.id in report_reply_ids %}

              {% else %}
                <p style="margin-left:5%">
              <span class="font-weight-bold text-primary">
                  {{ reply.user.first_name }} {{ reply.user.last_name }} :
              </span>
                  <span>{{ reply.body }}</span>
                  <!-- <div class="float-right"> -->
                  {% if reply.user.id == request.user.id %}
                    <a href="{% url 'projects:deleteReply'  reply.comment.project.id reply.comment.id reply.id %}">
                      <i class="fa fa-trash fa-lg " aria-hidden="true"></i>
                    </a>
                    <a href="{% url 'projects:editReply'  reply.comment.project.id reply.comment.id reply.id %}">
                      <i class="fa fa-edit fa-lg " aria-hidden="true"></i>
                    </a>
                  {% else %}
                    <a href="{% url 'projects:reportReply' reply.comment.project.id reply.comment.id reply.id %}">
                      <i class="fa fa-ban text-danger fa-lg "></i>
                    </a>
                  {% endif %}
                  <!-- </div> -->
                </p>
              {% endif %}

            {% endfor %}
            {% if request.user.is_authenticated %}
              <a style="margin-left:5%;margin-bottom:2% " class="btn btn-primary" role="button"
                 href="{% url 'projects:newReply' comment.project.id comment.id %}">Add Reply</a><br/>
            {% endif %}

          </div>

        {% endif %}
      {% endfor %}


      {% if request.user.is_authenticated %}
        <div class="form-group col-xs-6">
          <form class="form-group" action="{% url 'projects:addComment' project.id %}" method="post">
            {% csrf_token %}

            <input class="form-control input-md" placeholder="Add Comment ..." type="text" name="body"/>
            <input class="btn btn-primary" type="submit" value="Add" name="submit"/>
          </form>
        </div>
      {% endif %}
    </div>
  {% endif %}
  {% if pictures %}
    {% for picture in pictures %}
      <a href="{{ picture.image.url }}">
        <img src="{{ picture.image.url }}" class="rounded mx-auto my-4" width="150" height="150"/>
      </a>
    {% endfor %}
  {% endif %}
</div>

{% endblock content %}